- name: Install dependencies
  tags: 'volumes'
  become: yes
  apt:
    name: ['xfsprogs'] 
    state: latest
    install_recommends: no
    update_cache: yes

# to formate the device 
- name: Make file system
  tags: 'volumes'
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

# check if the mounting point exists
- name: Checking folders
  tags: 'volumes'
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  with_items:
    - "{{ volumes }}"

# if the mounting point does not exit in the last step, we create a mounting point for it
- name: Create directory
  tags: 'volumes'
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"

# mount the volume to the instance
- name: Mount device
  tags: 'volumes'
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"
