# playbook file

- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance # instance depends on the aboves
    - role: openstack-volume-snapshot

- name: attach a volume
  hosts: localhost
  tasks:
  - name: attach volume to host
    os_server_volume:
      state: present
      server: "{{ item.0 }}"
      volume: "{{ item.1  }}"
      device: /dev/vdb
    with_together:
      - '{{ os_instance_ids}}' 
      - '{{ os_vol_ids }}' 
